import os
import requests

def generate_voiceover():
    # ElevenLabs Keys Rotation
    api_keys = [
        os.environ.get("ELEVENLABS_API_KEY"),
        os.environ.get("ELEVENLABS_API_KEY_2"),
        os.environ.get("ELEVENLABS_API_KEY_3")
    ]
    
    # Clean keys list
    api_keys = [key for key in api_keys if key]
    
    if not api_keys:
        raise ValueError("No ElevenLabs API keys found in environment variables!")

    # Read the script generated by script_generator.py
    if not os.path.exists("script.txt"):
        raise FileNotFoundError("script.txt not found. Make sure script_generator.py ran successfully.")
        
    with open("script.txt", "r", encoding="utf-8") as f:
        script_text = f.read()

    # Voice ID: Energetic Male Accent (ElevenLabs)
    # Note: 'pNInz6obpgDQGcFmaJgB' works great for fast/energetic male narration with multilingual v2
    VOICE_ID = "pNInz6obpgDQGcFmaJgB"
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"

    payload = {
        "text": script_text,
        "model_id": "eleven_multilingual_v2",  # Best model for Hindi/Hinglish Indian accents
        "voice_settings": {
            "stability": 0.40,        # Lower stability = more energetic & expressive variation
            "similarity_boost": 0.75,
            "style": 0.45,            # Higher style = more natural emotion & human pauses
            "use_speaker_boost": True
        }
    }

    success = False
    for idx, key in enumerate(api_keys):
        headers = {
            "Accept": "audio/mpeg",
            "Content-Type": "application/json",
            "xi-api-key": key
        }
        
        print(f"Trying ElevenLabs Key #{idx + 1}...")
        response = requests.post(url, json=payload, headers=headers)
        
        if response.status_code == 200:
            with open("audio.mp3", "wb") as f:
                f.write(response.content)
            print("SUCCESS: Voiceover generated with Bunty/Energetic accent!")
            success = True
            break
        else:
            print(f"Key #{idx + 1} failed or out of quota (Status {response.status_code}). Trying next key...")

    if not success:
        raise RuntimeError("All 3 ElevenLabs API keys failed or ran out of quota.")

if __name__ == "__main__":
    generate_voiceover()
